sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
before_install:
  - gem install bundler -v 1.17.2
  - cp -r spec/data/test.git spec/data/test/.git && cd spec/data/test && git checkout test.rb && cd -
